name: build

on:
  push:
    paths:
      - 'AirISP/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux-arm,linux-x64,win-x86,win-x64,win-arm,osx-x64
        dotnetos: [linux, win, osx]
        dotnetarch: [x86, x64, arm, arm64]
        exclude:
          - dotnetos: linux
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: arm
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: environment prepare
        run: |
          curl -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh | bash /dev/stdin --channel STS
      - name: build
        env:
          DOTNETOS: ${{ matrix.dotnetos }}
          DOTNETARCH: ${{ matrix.dotnetarch }}
        run: |
          cd AirISP
          if [ "$DOTNETOS-$DOTNETARCH" = "osx-arm64" ]; then export SINGLE_FILE=false; else export SINGLE_FILE=true; fi
          dotnet publish -r $DOTNETOS-$DOTNETARCH -p:PublishSingleFile=$SINGLE_FILE -p:PublishTrimmed=true --self-contained true
          mkdir pkg
          mv bin/Debug/net7.0/$DOTNETOS-$DOTNETARCH/publish/* pkg/

      - uses: actions/upload-artifact@v3
        with:
          name: AirISP-${{ matrix.dotnetos }}-${{ matrix.dotnetarch }}
          path: AirISP/pkg/
