name: build

on:
  push:
    paths:
      - 'AirISP/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux-arm,linux-x64,win-x86,win-x64,win-arm,osx-x64
        dotnetos: [linux, win, osx]
        dotnetarch: [x86, x64, arm, arm64]
        exclude:
          - dotnetos: linux
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: arm
          - dotnetos: osx
            dotnetarch: arm64
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: environment prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0
      - name: build
        env:
          DOTNETOS: ${{ matrix.dotnetos }}
          DOTNETARCH: ${{ matrix.dotnetarch }}
        run: |
          cd AirISP
          dotnet publish -r $DOTNETOS-$DOTNETARCH -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          mkdir pkg
          mv bin/Debug/net6.0/$DOTNETOS-$DOTNETARCH/publish/* pkg/

      - uses: actions/upload-artifact@v3
        with:
          name: AirISP-${{ matrix.dotnetos }}-${{ matrix.dotnetarch }}
          path: AirISP/pkg/
